apiVersion: v1
kind: Service
metadata:
    name: redis-service
    labels:
        app: voting-app
        type: services
spec:
    type: NodePort
    ports:
        - targetPort: 6379
          port: 6379
          nodePort: 40080
    selector:
        matchLabels:
            name: redis-pod
            app: voting-app
            type: messaging