apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-deploy
    labels:
        app: voting-app
        type: messaging
spec:
    replicas: 1
    selector:
        matchLabels:
            name: redis-pod
            app: voting-app
            type: messaging
    template:
        metadata:
            name: redis-pod
            labels:
                name: redis-pod
                app: voting-app
                type: messaging
        spec:
            containers:
                - name: redis-pod
                  image: redis
                  ports:
                    - containerPort: 6379