apiVersion: apps/v1
kind: Deployment
metadata:
    name: result-deploy
    labels:
        app: voting-app
        type: web
spec:
    replicas: 2
    selector:
        matchLabels:
            name: result-pod
            app: voting-app
            type: web
    template:
        metadata:
            name: result-pod
            labels:
                name: result-pod
                app: voting-app
                type: web
        spec:
            containers:
                - name: result-cont
                  image: dockersamples/examplevotingapp_result
                  ports:
                    - containerPort: 80