apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
  labels:
    app: voting-app
    type: web
spec:
  replicas: 2
  selector:
    matchLabels:
        name: voting-pod
        app: voting-app
        type: web
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
        app: voting-app
        type: web
    spec:
      containers:
        - name: voting-cont
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80